"""empty message

Revision ID: 769797f28d86
Revises: 1d69ec6fd4a2
Create Date: 2023-06-19 21:32:17.057371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769797f28d86'
down_revision = '1d69ec6fd4a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mental_health_resources',
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('resource_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mental_health_resources')
    # ### end Alembic commands ###
